title: My crafting blog
author: Sandri fa Toren
description: Crafting projects and such
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

collections:
  knitting:
    output: true
    permalink: /knitting/:title/
  blackwork:
    output: true
    permalink: /blackwork/:title/
  quilting:
    output: true
    permalink: /quilting/:title/
